version: "3.9"

services:
  collage:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - tmp:/app/tmp
    depends_on:
      - worker
    restart: always
    command: ["npx", "nest", "start", "collage"]

  worker:
    build: .
    env_file:
      - .env
    volumes:
      - tmp:/app/tmp
    restart: always
    command: ["npx", "nest", "start", "worker"]


volumes:
  tmp: